export const SET_STATE = 'SET_STATE';
export const SET_ORIGINAL_PROJECT = 'SET_ORIGINAL_PROJECT';
export const SET_TO_BE_ADDED_PROJECT = 'SET_TO_BE_ADDED_PROJECT';
export const ADD_LABEL = 'ADD_LABEL';
export const REMOVE_LABEL = 'REMOVE_LABEL';
export const EDIT_LABEL = 'EDIT_LABEL';

export const TOGGLE_AUTHENTICATE = 'TOGGLE_AUTHENTICATE';
export const SET_TOKEN = 'SET TOKEN';
